#pragma once

#include "Ham/Core/Base.h"

#define HAM_ENABLE_PROFILING (USE_OPTICK && 0)
#if defined(HAM_ENABLE_PROFILING) && HAM_ENABLE_PROFILING
#define HAM_PROFILE_APP(...)           OPTICK_APP(__VA_ARGS__)
#define HAM_PROFILE_THREAD(...)        OPTICK_THREAD(__VA_ARGS__)
#define HAM_PROFILE_FRAME(...)         OPTICK_FRAME(__VA_ARGS__)
#define HAM_PROFILE_SCOPE(...)         OPTICK_EVENT(__VA_ARGS__)
#define HAM_PROFILE_BEGIN_SESSION(...) OPTICK_START_CAPTURE(__VA_ARGS__)
#define HAM_PROFILE_END_SESSION(...)   OPTICK_STOP_CAPTURE(__VA_ARGS__)
#define HAM_PROFILE_SAVE_SESSION(...)  OPTICK_SAVE_CAPTURE(__VA_ARGS__)
#else
#define HAM_PROFILE_APP(...)
#define HAM_PROFILE_THREAD(...)
#define HAM_PROFILE_FRAME(...)
#define HAM_PROFILE_SCOPE(...)
#define HAM_PROFILE_BEGIN_SESSION(...)
#define HAM_PROFILE_END_SESSION(...)
#define HAM_PROFILE_SAVE_SESSION(...)
#endif